apiVersion: v1
kind: Service
metadata:
  name: raheem-web-service
spec:
  # INTENT: Change type from NodePort to LoadBalancer
  type: LoadBalancer 
  selector:
    app: flask 
  ports:
    - protocol: TCP
      port: 80         # The port the world sees
      targetPort: 5000   # The port your Python app listens on